export HCP_ORGANIZATION_ID="None"
export HCP_PROJECT_ID="None"
export HCP_CLIENT_ID="None"
export HCP_CLIENT_SECRET="None"
export TFE_ORG="None"
export TFE_TOKEN="None"
export TFE_WORKSPACE="None"
export HCP_CLIENT_TOKEN="None"
