apiVersion: hostpathprovisioner.kubevirt.io/v1beta1
kind: HostPathProvisioner
metadata:
  name: hostpath-provisioner
spec:
  imagePullPolicy: IfNotPresent
  storagePools:
    - name: vmdata
      path: "/var/myvolumes"
workload:
  nodeSelector:
    kubernetes.io/os: linux
