apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: centos-vm
  name: centos-vm
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: centos-vm
      spec:
        source:
          pvc:
            namespace: "default"
            name: "centos-vm-packer"
        storage:
          resources:
            requests:
              storage: 20Gi
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: centos-vm
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 2
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              name: default
          rng: {}
        resources:
          requests:
            memory: 8Gi
      evictionStrategy: LiveMigrate
      networks:
        - name: default
          pod: {}
      volumes:
        - dataVolume:
            name: centos-vm
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: cloud-user
              password: 'passw0rd' 
              chpasswd: { expire: False }
          name: cloudinitdisk
