apiVersion: hostpathprovisioner.kubevirt.io/v1beta1
kind: HostPathProvisioner
metadata:
  name: hostpath-provisioner
spec:
  imagePullPolicy: IfNotPresent
  storagePools:
    - name: vmdata
      path: "/var/myvolumes"
      pvcTemplate:
        volumeMode: Block
        storageClassName: hostpath-csi
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
  workload:
    nodeSelector:
      kubernetes.io/os: linux
