- name: configure webserver
  hosts: webserver
  tasks:
    - name: Add epel-release repo
      yum:
        name: epel-release
        state: present
    - name: install nginx
      yum:
        name: nginx
    - name: Push Default config
      copy:
        src: nginx.conf
        dest: /etc/nginx/
    - name: Push Default config
      copy:
        src: default.conf
        dest: /etc/nginx/conf.d/
    - name: Deploy webpage
      copy:
        src: index.html
        dest: /usr/share/nginx/html
